# Generated by Django 3.2.13 on 2022-04-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quanitity',
            new_name='quantity',
        ),
    ]
